### ISSUE TITLE
Window crash: invalid or unexpected token

### ISSUE THREAD

**Issue by urbanio** [YZYLAB/dream-js#3]
Node version v11.6.0

How to reproduce:
1. git clone
2. npm i
3. node example
4. window appear, site loaded, crash

```js
$ node example
SyntaxError: Invalid or unexpected token
    at new Function (<anonymous>)
    at Proxy.compile (D:\Table\Downloads\dream-js\node_modules\minstache\index.j
s:79:10)
    at execute (D:\Table\Downloads\dream-js\lib\javascript.js:14:22)
    at Dream.evaluate_now (D:\Table\Downloads\dream-js\lib\dream.js:373:20)
    at Dream.evaluate (D:\Table\Downloads\dream-js\lib\actions.js:627:23)
    at Dream.next (D:\Table\Downloads\dream-js\lib\dream.js:333:14)
    at self.child.call (D:\Table\Downloads\dream-js\lib\dream.js:340:48)
    at Object.<anonymous> (D:\Table\Downloads\dream-js\lib\ipc.js:93:18)
    at Object.onceWrapper (events.js:276:13)
    at Object.emit (events.js:188:13)
```

**Comment by olvrschwrz** [comment]
#4 will fix it

**Comment by YZYLAB** [comment]
Merged @olvrschwrz
